server:
  port: 14443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: "classpath:keystore/keystore.p12"
    key-store-password: "changeit"
    protocol: TLS
    enabled-protocols: TLSv1.2