spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:mysql://localhost:3306/ttbb
    username: hzj
    password: Mysql@123
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        jdbc:
          lob:
            non_contextual_creation: true
